export default {
    type:{
        type:String,
        default:'default'
    },
    plain:{
        type:Boolean,
        default:false
    },
    round:{
        type:Boolean,
        default:false
    },
    circle:{
        type:Boolean,
        default:false
    },
    icon:{
        type:String
    },
    disabled:{
        type:Boolean,
        default:false
    },
    loading:{
        type:Boolean,
        default:false
    },
    size:{
        type:String,
    }
}